### ISSUE TITLE
Integer division

### ISSUE THREAD

**Issue by gxavier38** [meilof/pysnark#15]
Would it be possible for divisions like
```
PrivVal(2) / PrivVal(3)
```
to return a `LinCombFxp` rather than throwing a `ValueError`?

**Comment by meilof** [comment]
You can convert them to LinCombFxp by doing LinCombFxp.doconvert(var,True).
Not sure if it should be the default behaviour for LinComb, I will think
about it.

Op di 18 mei 2021 22:53 schreef Glenn Xavier ***@***.***>:

**Comment by gxavier38** [comment]
Thanks! I got it working with:
```
LinCombFxp.fromvar(PrivVal(1), True)
```
