### ISSUE TITLE
NameError 'gmpy' is not defined

### ISSUE THREAD

**Issue by SopmmmodII** [meilof/pysnark#5]
I tried to run some examples with qaptools as backend, and it comes the error.
"NameError: name 'gmpy' is not defined"
Then I edited the function at backend.py.
"def fieldinverse(val):
    #return int(gmpy.invert(val, vc_p))
    return int(pysnark.gmpy.invert(val,vc_p))"
And it works fine.

**Comment by meilof** [comment]
Thanks for reporting! Fixed now as you suggested.
