### ISSUE TITLE
Key material too small and missing master secret key error for example cube.py using qaptools backend

### ISSUE THREAD

**Issue by lepilotedef22** [meilof/pysnark#6]
Hello,
I recently installed your library and as a first step I tried the example that you suggest, cube.py, using qaptools backend.
I first ran the code as the trusted third party. It successfully generated all the files.
Then I created a prover folder in which I copy-pasted the cube.py source as well as all the required files listed in the [README](https://github.com/meilof/pysnark#using-pysnark-qaptools-backend), namely:

- `pysnark_schedule`
- `pysnark_masterek`
- `pysnark_ek_main`
- `pysnark_eqs_main`
The I executed the code in this folder, and ran into this error:
```Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/denisverstraeten/Envs/anonymous-auction380/lib/python3.8/site-packages/pysnark/qaptools/backend.py", line 165, in prove
    cursz, curpubsz = runqapgen.ensure_mkey(sz, pubsz)
  File "/Users/denisverstraeten/Envs/anonymous-auction380/lib/python3.8/site-packages/pysnark/qaptools/runqapgen.py", line 115, in ensure_mkey
    raise IOError("Key material too small ("+str(curek)+","+str(curpk)+
OSError: Key material too small (8,-1)<(8,2) and missing master secret key
```
By following the traceback, it appeared that `curpk` is equal to -1. `curpk` is defined as `curpk=get_mpkey_size()` (line 105 of qaptools/runqapgen.py).
Looking at the function `get_mpkey_size` (line 74 of the same file), the value -1 is returned if there is an `IOError`, which, in this case in my opinion , comes from `mpkf = open(options.get_mpkey_file()) `(line 81).
Then, by inspecting the function `get_mpkey_file` (line 57 of qaptools/options.py), which returns 'pysnark_masterpk', I deduced that for the prover to be able to compute the proof, I needed to include the file `pysnark_masterpk` into the prover folder. And indeed, by doing so, the proof (as well as the verification) worked.
Is there something that I did wrong in the way that I followed the small example tutorial ? Moreover, in the previous discussion, nothing is linked especially to the cube example, I have the impression that any proof would lead to the same error. Should `pysnark_masterpk` be given to the prover in any case ?
Thank you very much for your answer,
Have a nice day,
Denis

**Comment by meilof** [comment]
Hey Denis,

That’s well spotted! Yes, it seems that the prover code assumes that the master public key is there. I think it should be possible to get rid of this requirement, but then again, having to copy the file is probably not that big a problem.

I will correct this in the README file, thanks!

Cheers,
Meilof
